- name: Create /root/BootcBlade.containerfile
  ansible.builtin.template:
    src: "bootcblade.containerfile.j2"
    dest: "/root/bootcblade.containerfile"

- name: Build BootcBlade container image
  ansible.builtin.shell: "podman build -t localhost/bootcblade -f /root/bootcblade.containerfile --no-cache --pull=always"
